### ISSUE TITLE
Auto fill names

### ISSUE THREAD

**Issue by awc3003** [r1ch/witb#1]
I'm a very busy important person and I don't have time to list names. Integrate with this or I'll demand my investment back.

https://en.wikipedia.org/w/api.php?action=query&format=xml&gatfrom=Persondata&gatlimit=100&generator=alltransclusions

**Comment by r1ch** [comment]
Thanks for this - sorry I have turned off all notifications as I get bombarded by them

This looks like a very good feature - I look forward to reviewing your PR (this is the standard passive aggressive approach to these I believe)

I will now tag this in multiple unhelpful ways and remove some tags later today

**Comment by r1ch** [comment]
Having reviewed this I think this is a awful
